name = "yahtzee-game"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2023-10-01"

[build]
command = "npm run build"
output_directory = "out"

[site]
bucket = "out"
entry-point = "./"

[env.production]
name = "yahtzee-game-production"
zone_id = ""
route = ""

pages_build_output_dir = "out" 